[platformio]
default_envs = esp32-s3-wifitest

[env:esp32-s3-wifitest]
platform = espressif32@^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 115200
board_upload.use_1200bps_touch = no
board_upload.wait_for_upload_port = no
upload_flags =
  --before=no_reset
  --after=hard_reset
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D WIFI_SSID=\"MATHEWS-2.4G\"
  -D WIFI_PASSWORD=\"mathews@123\"
