[platformio]
default_envs = esp32-oled

[env]
platform = espressif32@^6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D POS_ID=\"POS-001\"
  -D PAYMENT_TTL_SEC=300
  -D QRCODEVERSION=5
  -D WIFI_SSID=\"\"
  -D WIFI_PASSWORD=\"\"
  -D SUBMIT_URL=\"\"
  -D SUPABASE_ANON_KEY=\"\"

[env:esp32-oled]
build_flags =
  ${env.build_flags}
  -D DISPLAY_OLED=1
lib_deps =
  chris--a/Keypad@^3.1.1
  yoprogramo/QRcodeDisplay@^2.0.0
  yoprogramo/QRcodeOled@^2.0.0
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.0
  h2zero/NimBLE-Arduino@^2.1.0
  bblanchon/ArduinoJson@^7.2.0

[env:esp32-tft]
build_flags =
  ${env.build_flags}
  -D DISPLAY_TFT=1
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=4
  -D LOAD_GLCD=1
  -D SPI_FREQUENCY=27000000
lib_deps =
  chris--a/Keypad@^3.1.1
  yoprogramo/QRcodeDisplay@^2.0.0
  https://github.com/yoprogramo/QRcode_eSPI.git
  bodmer/TFT_eSPI@^2.5.43
  h2zero/NimBLE-Arduino@^2.1.0
  bblanchon/ArduinoJson@^7.2.0
